name: Email Sticker Sender

on:
  pull_request:
    types:
      - opened

jobs:
  send-sticker-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'  # Replace with a valid Node.js version

    - name: Install msmtp
      run: sudo apt-get install -y msmtp

    - name: Set up SMTP Config
      run: |
        MSMTPRC_PATH=$HOME/.msmtprc
        echo "account default" >> $MSMTPRC_PATH
        echo "host ${{ secrets.SMTP_HOST }}" >> $MSMTPRC_PATH
        echo "port ${{ secrets.SMTP_PORT }}" >> $MSMTPRC_PATH
        echo "protocol smtp" >> $MSMTPRC_PATH
        echo "auth on" >> $MSMTPRC_PATH
        echo "from ${{ secrets.SMTP_USER }}" >> $MSMTPRC_PATH
        echo "user ${{ secrets.SMTP_USER }}" >> $MSMTPRC_PATH
        echo "password ${{ secrets.SMTP_PASSWORD }}" >> $MSMTPRC_PATH
        chmod 600 $MSMTPRC_PATH
      env:
        MSMTPRC_PATH: $HOME/.msmtprc

    - name: Get PR Author's Email
      id: get-author-email
      run: |
        PR_AUTHOR_EMAIL=$(curl -sH "Authorization: token $GITHUB_TOKEN" \
                          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}" | \
                          jq -r '.user.email')
        if [[ "$PR_AUTHOR_EMAIL" == "null" || "$PR_AUTHOR_EMAIL" == "undefined" ]]; then
          echo "PR_AUTHOR_EMAIL not available or set to 'null'. Exiting..."
          exit 1
        fi
        echo "PR_AUTHOR_EMAIL=$PR_AUTHOR_EMAIL" >> $GITHUB_ENV

    - name: Get Collaborators' Emails
      id: get-collaborators-emails
      run: |
        COLLABORATORS_EMAILS=$(curl -sH "Authorization: token $GITHUB_TOKEN" \
                                "https://api.github.com/repos/${{ github.repository }}/collaborators" | \
                                jq -r '.[].permissions.pusher + " " + .[].permissions.admin')
        echo "COLLABORATORS_EMAILS=$COLLABORATORS_EMAILS" >> $GITHUB_ENV

    - name: Send Sticker Email
      run: |
        echo "Subject: Thank you for the Pull Request!" | msmtp --file=$MSMTPRC_PATH --read-recipients
        echo "Content-Type: text/plain; charset=utf-8" | msmtp --file=$MSMTPRC_PATH --read-recipients
        echo "" | msmtp --file=$MSMTPRC_PATH --read-recipients
        echo "🎉 Thank you for opening this pull request!" | msmtp ${{ env.PR_AUTHOR_EMAIL }} ${{ env.COLLABORATORS_EMAILS }}
      env:
        PR_AUTHOR_EMAIL: ${{ env.PR_AUTHOR_EMAIL }}
        COLLABORATORS_EMAILS: ${{ env.COLLABORATORS_EMAILS }}
